version: 1.5.{build}
image: Visual Studio 2017



environment:
  matrix:
  - PlatformToolset: v141_xp
  - PlatformToolset: v140_xp

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NotepadSharp.vcxproj /m /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin64\NotepadSharp.dll" -FileName NotepadSharp.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\NotepadSharp.dll" -FileName NotepadSharp.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v141_xp") {
            if($env:PLATFORM_INPUT -eq "x64"){
            $ZipFileName = "NotepadSharp_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            Remove-Item bin64\*.ipdb
            Remove-Item bin64\*.iobj
            7z a $ZipFileName bin64\*
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
            $ZipFileName = "NotepadSharp_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            Remove-Item bin\*.ipdb
            Remove-Item bin\*.iobj
            7z a $ZipFileName bin\*
            }
        }

artifacts:
  - path: NotepadSharp_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: PhNXrhw03Z0rJZssX/UYyoIofw669wU1GBy/hGq+WJPCXd7mbxDu6Il32Rx0LBH6
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v141_xp
        configuration: Release